### ISSUE TITLE
159p의 박스 "rest와 next의 비교" 설명에서 맨 마지막 문장 앞문장 번역

### ISSUE THREAD

**Issue by practice** [ksseono/the-joy-of-clojure#1]
구글 그룹스에도 썼는데, 여기에 올리는 것이 더 나을 것 같네요...

159p의 박스 "rest와 next의 비교" 설명에서 맨 마지막 문장 앞문장이 좀 ...

번역문:
"`next`를 사용하면 지연 시퀀스의 한 개 요소가 덜 지연되도록 함으로써 비용이 높으면 실체화되지 않도록 만든다."

원문: 
Using `next` causes a lazy seq to be one element less lazy, which might not be desired if the cost of realization is expensive. 

제 생각:
"`next`를 사용하면 지연 시퀀스의 한 개 요소가 덜 지연되는데, 실체화하는 데에 들어가는 비용이 높다면 바람직 하지 않을 수 있다."

어떠세요?

**Comment by ksseono** [comment]
의견 감사합니다! 지금보니 제가 잘못 번역한 것이 맞네요 ^^; 주신 의견이 적절해 보입니다.
