### ISSUE TITLE
162p 세째줄

### ISSUE THREAD

**Issue by practice** [ksseono/the-joy-of-clojure#2]
번역:
순수함수형 지연 언어**에 비해** 뛰어난 점이라고...

원문:
This is one area where a purely functional lazy language such as Haskell (Thompson 1999) shines by comparison.

제 생각:
순수 함수형 지연 언어**가 비교적 더** 뛰어난 점이라고...

**Comment by practice** [comment]
하스켈이 더 낫다라고 얘기되어야 하는데 반대로 번역된 것 같습니다.

**Comment by ksseono** [comment]
감사합니다! 반영하겠습니다 ~
