### ISSUE TITLE
p.397 예제13.6 오디오함수 API 변경으로 인하여 코드 동작 안함.

### ISSUE THREAD

**Issue by soulawaker** [ksseono/the-joy-of-clojure#4]
변경 내용은 아래 링크에 나옵니다.
https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Porting_webkitAudioContext_code_to_standards_based_AudioContext

대상들을 적어보면 아래와 같습니다.
.createGainNode 는 .createGain 으로 변경
.noteOn은 .start로, 
.noteOff는 .stop으로 변경

추가로 해당 예제에서 update-in-note 로 잘못 인쇄된 함수명을 update-in 과 note로 분리해줘야 합니다.

**Comment by ksseono** [comment]
저도 해당 문제를 파악하고 소스코드 상에서는 이렇게 반영했던 것 같습니다  => https://github.com/ksseono/the-joy-of-clojure/blob/master/src/clj/ch13/joy/externs_for_cljs.clj#L105

책 내용에 적용 반영을 못한 것 같기도 하네요. 확인해보겠습니다. 감사합니다!

**Comment by soulawaker** [comment]
music.cljs 에 수정이 이미 되어 있더군요. 위키에 반영했습니다.
