### ISSUE TITLE
p.449 relative-units 실행에 대한 예외값 잘못 표기?

### ISSUE THREAD

**Issue by soulawaker** [ksseono/the-joy-of-clojure#6]
CompilerException이 아니라
RuntimeException Undefined unit :ramsden-chain joy.unit/relative-unit
이 예외가 발생되는 것이 맞는 것으로 보입니다.

**Comment by ksseono** [comment]
확인 후 위키에 반영하겠습니다 (시간이 되신다면 먼저 해주셔도 좋구요 ^^;)
